version: '3'

services:
  emqx:
    image: emqx/emqx:latest
    restart: always
    environment:
      EMQX_NAME: emqx_local
      EMQX_HOST: 127.0.0.1
    ports:
      - "1883:1883"
      - "8084:8084"
      - "8883:8883"
      - "8083:8083"
      - "18083:18083"
    volumes:
      - vol-emqx-data:/opt/emqx/data
      - vol-emqx-etc:/opt/emqx/etc
      - vol-emqx-log:/opt/emqx/log

volumes:
  vol-emqx-data:
    name: foo-emqx-data
  vol-emqx-etc:
    name: foo-emqx-etc
  vol-emqx-log:
    name: foo-emqx-log

